### ISSUE TITLE
PUNCH_IN doesn't function

### ISSUE THREAD

**Issue by femee24** [maestrano/timetrex#32]
Hi
would like to ask if you are familiar with this issue

{"api_retval":false,"api_details":{"code":"VALIDATION","description":"INVALID DATA","record_details":{"total":1,"valid":0,"invalid":1},"user_generic_status_batch_id":false,"request":false,"pager":false,"details":[{"status":["Status not specified"],"type":["Type not specified"],"time_stamp":["Time stamp not specified"]}]}}

Failed to load resource: the server responded with a status of 500 (Internal Server Error)

whenever I click the save button on the punch in I would have an error of 
POST API:
{"api_retval":false,"api_details":{"code":"EXCEPTION","description":"Method setUserPu\u**_randomnumbers_** does not exist.","record_details":{"total":0,"valid":0,"invalid":0},"user_generic_status_batch_id":false,"details":false}}

Kindly advised of what I should do
thank you

**Comment by BrunoChauvet** [comment]
Hi,
I have never seen this issue before. You can contact the TimeTrex community on their forum, they may be able to help: https://forums.timetrex.com
